/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppSaleIndexRouteImport } from './routes/_app/sale/index'
import { Route as AppRentalIndexRouteImport } from './routes/_app/rental/index'
import { Route as AppRentalRentalSaleRouteImport } from './routes/_app/rental/rental-sale'
import { Route as AppRentalEquipStatusRouteImport } from './routes/_app/rental/equip-status'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSaleIndexRoute = AppSaleIndexRouteImport.update({
  id: '/sale/',
  path: '/sale/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRentalIndexRoute = AppRentalIndexRouteImport.update({
  id: '/rental/',
  path: '/rental/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRentalRentalSaleRoute = AppRentalRentalSaleRouteImport.update({
  id: '/rental/rental-sale',
  path: '/rental/rental-sale',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRentalEquipStatusRoute = AppRentalEquipStatusRouteImport.update({
  id: '/rental/equip-status',
  path: '/rental/equip-status',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteRoute
  '/settings': typeof AppSettingsRouteRoute
  '/rental/equip-status': typeof AppRentalEquipStatusRoute
  '/rental/rental-sale': typeof AppRentalRentalSaleRoute
  '/rental': typeof AppRentalIndexRoute
  '/sale': typeof AppSaleIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRouteRoute
  '/settings': typeof AppSettingsRouteRoute
  '/rental/equip-status': typeof AppRentalEquipStatusRoute
  '/rental/rental-sale': typeof AppRentalRentalSaleRoute
  '/rental': typeof AppRentalIndexRoute
  '/sale': typeof AppSaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/_app/settings': typeof AppSettingsRouteRoute
  '/_app/rental/equip-status': typeof AppRentalEquipStatusRoute
  '/_app/rental/rental-sale': typeof AppRentalRentalSaleRoute
  '/_app/rental/': typeof AppRentalIndexRoute
  '/_app/sale/': typeof AppSaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/settings'
    | '/rental/equip-status'
    | '/rental/rental-sale'
    | '/rental'
    | '/sale'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/rental/equip-status'
    | '/rental/rental-sale'
    | '/rental'
    | '/sale'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/settings'
    | '/_app/rental/equip-status'
    | '/_app/rental/rental-sale'
    | '/_app/rental/'
    | '/_app/sale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sale/': {
      id: '/_app/sale/'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof AppSaleIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rental/': {
      id: '/_app/rental/'
      path: '/rental'
      fullPath: '/rental'
      preLoaderRoute: typeof AppRentalIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rental/rental-sale': {
      id: '/_app/rental/rental-sale'
      path: '/rental/rental-sale'
      fullPath: '/rental/rental-sale'
      preLoaderRoute: typeof AppRentalRentalSaleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rental/equip-status': {
      id: '/_app/rental/equip-status'
      path: '/rental/equip-status'
      fullPath: '/rental/equip-status'
      preLoaderRoute: typeof AppRentalEquipStatusRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRoute
  AppRentalEquipStatusRoute: typeof AppRentalEquipStatusRoute
  AppRentalRentalSaleRoute: typeof AppRentalRentalSaleRoute
  AppRentalIndexRoute: typeof AppRentalIndexRoute
  AppSaleIndexRoute: typeof AppSaleIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRoute,
  AppRentalEquipStatusRoute: AppRentalEquipStatusRoute,
  AppRentalRentalSaleRoute: AppRentalRentalSaleRoute,
  AppRentalIndexRoute: AppRentalIndexRoute,
  AppSaleIndexRoute: AppSaleIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
