/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppSaleIndexRouteImport } from './routes/_app/sale/index'
import { Route as AppRentalIndexRouteImport } from './routes/_app/rental/index'
import { Route as AppRegisterIndexRouteImport } from './routes/_app/register/index'
import { Route as AppRentalRentalSaleRouteImport } from './routes/_app/rental/rental-sale'
import { Route as AppRentalEquipStatusRouteImport } from './routes/_app/rental/equip-status'
import { Route as AppRegisterSubcategoryRouteImport } from './routes/_app/register/subcategory'
import { Route as AppRegisterItemRouteImport } from './routes/_app/register/item'
import { Route as AppRegisterClientRouteImport } from './routes/_app/register/client'
import { Route as AppRegisterCardRouteImport } from './routes/_app/register/card'
import { Route as AppRegisterBranchRouteImport } from './routes/_app/register/branch'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSaleIndexRoute = AppSaleIndexRouteImport.update({
  id: '/sale/',
  path: '/sale/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRentalIndexRoute = AppRentalIndexRouteImport.update({
  id: '/rental/',
  path: '/rental/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRegisterIndexRoute = AppRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRentalRentalSaleRoute = AppRentalRentalSaleRouteImport.update({
  id: '/rental/rental-sale',
  path: '/rental/rental-sale',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRentalEquipStatusRoute = AppRentalEquipStatusRouteImport.update({
  id: '/rental/equip-status',
  path: '/rental/equip-status',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRegisterSubcategoryRoute = AppRegisterSubcategoryRouteImport.update({
  id: '/register/subcategory',
  path: '/register/subcategory',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRegisterItemRoute = AppRegisterItemRouteImport.update({
  id: '/register/item',
  path: '/register/item',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRegisterClientRoute = AppRegisterClientRouteImport.update({
  id: '/register/client',
  path: '/register/client',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRegisterCardRoute = AppRegisterCardRouteImport.update({
  id: '/register/card',
  path: '/register/card',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRegisterBranchRoute = AppRegisterBranchRouteImport.update({
  id: '/register/branch',
  path: '/register/branch',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteRoute
  '/settings': typeof AppSettingsRouteRoute
  '/register/branch': typeof AppRegisterBranchRoute
  '/register/card': typeof AppRegisterCardRoute
  '/register/client': typeof AppRegisterClientRoute
  '/register/item': typeof AppRegisterItemRoute
  '/register/subcategory': typeof AppRegisterSubcategoryRoute
  '/rental/equip-status': typeof AppRentalEquipStatusRoute
  '/rental/rental-sale': typeof AppRentalRentalSaleRoute
  '/register': typeof AppRegisterIndexRoute
  '/rental': typeof AppRentalIndexRoute
  '/sale': typeof AppSaleIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRouteRoute
  '/settings': typeof AppSettingsRouteRoute
  '/register/branch': typeof AppRegisterBranchRoute
  '/register/card': typeof AppRegisterCardRoute
  '/register/client': typeof AppRegisterClientRoute
  '/register/item': typeof AppRegisterItemRoute
  '/register/subcategory': typeof AppRegisterSubcategoryRoute
  '/rental/equip-status': typeof AppRentalEquipStatusRoute
  '/rental/rental-sale': typeof AppRentalRentalSaleRoute
  '/register': typeof AppRegisterIndexRoute
  '/rental': typeof AppRentalIndexRoute
  '/sale': typeof AppSaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/_app/settings': typeof AppSettingsRouteRoute
  '/_app/register/branch': typeof AppRegisterBranchRoute
  '/_app/register/card': typeof AppRegisterCardRoute
  '/_app/register/client': typeof AppRegisterClientRoute
  '/_app/register/item': typeof AppRegisterItemRoute
  '/_app/register/subcategory': typeof AppRegisterSubcategoryRoute
  '/_app/rental/equip-status': typeof AppRentalEquipStatusRoute
  '/_app/rental/rental-sale': typeof AppRentalRentalSaleRoute
  '/_app/register/': typeof AppRegisterIndexRoute
  '/_app/rental/': typeof AppRentalIndexRoute
  '/_app/sale/': typeof AppSaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/settings'
    | '/register/branch'
    | '/register/card'
    | '/register/client'
    | '/register/item'
    | '/register/subcategory'
    | '/rental/equip-status'
    | '/rental/rental-sale'
    | '/register'
    | '/rental'
    | '/sale'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/register/branch'
    | '/register/card'
    | '/register/client'
    | '/register/item'
    | '/register/subcategory'
    | '/rental/equip-status'
    | '/rental/rental-sale'
    | '/register'
    | '/rental'
    | '/sale'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/settings'
    | '/_app/register/branch'
    | '/_app/register/card'
    | '/_app/register/client'
    | '/_app/register/item'
    | '/_app/register/subcategory'
    | '/_app/rental/equip-status'
    | '/_app/rental/rental-sale'
    | '/_app/register/'
    | '/_app/rental/'
    | '/_app/sale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sale/': {
      id: '/_app/sale/'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof AppSaleIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rental/': {
      id: '/_app/rental/'
      path: '/rental'
      fullPath: '/rental'
      preLoaderRoute: typeof AppRentalIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/register/': {
      id: '/_app/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rental/rental-sale': {
      id: '/_app/rental/rental-sale'
      path: '/rental/rental-sale'
      fullPath: '/rental/rental-sale'
      preLoaderRoute: typeof AppRentalRentalSaleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rental/equip-status': {
      id: '/_app/rental/equip-status'
      path: '/rental/equip-status'
      fullPath: '/rental/equip-status'
      preLoaderRoute: typeof AppRentalEquipStatusRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/register/subcategory': {
      id: '/_app/register/subcategory'
      path: '/register/subcategory'
      fullPath: '/register/subcategory'
      preLoaderRoute: typeof AppRegisterSubcategoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/register/item': {
      id: '/_app/register/item'
      path: '/register/item'
      fullPath: '/register/item'
      preLoaderRoute: typeof AppRegisterItemRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/register/client': {
      id: '/_app/register/client'
      path: '/register/client'
      fullPath: '/register/client'
      preLoaderRoute: typeof AppRegisterClientRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/register/card': {
      id: '/_app/register/card'
      path: '/register/card'
      fullPath: '/register/card'
      preLoaderRoute: typeof AppRegisterCardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/register/branch': {
      id: '/_app/register/branch'
      path: '/register/branch'
      fullPath: '/register/branch'
      preLoaderRoute: typeof AppRegisterBranchRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRoute
  AppRegisterBranchRoute: typeof AppRegisterBranchRoute
  AppRegisterCardRoute: typeof AppRegisterCardRoute
  AppRegisterClientRoute: typeof AppRegisterClientRoute
  AppRegisterItemRoute: typeof AppRegisterItemRoute
  AppRegisterSubcategoryRoute: typeof AppRegisterSubcategoryRoute
  AppRentalEquipStatusRoute: typeof AppRentalEquipStatusRoute
  AppRentalRentalSaleRoute: typeof AppRentalRentalSaleRoute
  AppRegisterIndexRoute: typeof AppRegisterIndexRoute
  AppRentalIndexRoute: typeof AppRentalIndexRoute
  AppSaleIndexRoute: typeof AppSaleIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRoute,
  AppRegisterBranchRoute: AppRegisterBranchRoute,
  AppRegisterCardRoute: AppRegisterCardRoute,
  AppRegisterClientRoute: AppRegisterClientRoute,
  AppRegisterItemRoute: AppRegisterItemRoute,
  AppRegisterSubcategoryRoute: AppRegisterSubcategoryRoute,
  AppRentalEquipStatusRoute: AppRentalEquipStatusRoute,
  AppRentalRentalSaleRoute: AppRentalRentalSaleRoute,
  AppRegisterIndexRoute: AppRegisterIndexRoute,
  AppRentalIndexRoute: AppRentalIndexRoute,
  AppSaleIndexRoute: AppSaleIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
